# Project information
site_name: RingCentral Cloud Phone SDK
site_url: https://ringcentral.github.io/ringcentral-softphone-ts

# Repository
repo_url: https://github.com/ringcentral/ringcentral-softphone-ts
repo_name: ringcentral/ringcentral-softphone-ts
edit_uri: tree/main/docs
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.path
    #      - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - search.sharing
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - badges
  #  - with-pdf
  - exclude:
      regex:
        - '^\.#.*'
        - '.*\.\#.*$'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringcentral
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ringcentraldevs
extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - mdx_include
  - admonition
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

copyright: "2024-2025 RingCentral, Inc. All rights reserved."

nav:
  - "Home": index.md
  - "Getting stated": get-started.md
  - "Audio": audio.md
  - "Reference":
      - "Cloud Phone":
          - "Events":
              - "invite": reference/invite.md
              - "message": reference/message.md
          - "Methods":
              - "answer()": reference/answer.md
              - "call()": reference/call.md
              - "decline()": reference/decline.md
              - "enableDebugMode()": reference/enableDebugMode.md
      - "Call Session":
          - "Events":
              - "answered": reference/answered.md
              - "audioPacket": reference/audioPacket.md
              - "busy": reference/busy.md
              - "disposed": reference/disposed.md
              - "dtmf": reference/dtmf.md
              - "dtmfPacket": reference/dtmfPacket.md
              - "finished": reference/finished.md
              - "rtpPacket": reference/rtpPacket.md
          - "Methods":
              - "callId()": reference/callId.md
              - "dispose()": reference/dispose.md
              - "hangup()": reference/hangup.md
              - "send()": reference/send.md
              - "sendDTMF()": reference/sendDtmf.md
              - "sendPacket()": reference/sendPacket.md
              - "streamAudio()": reference/streamAudio.md
              - "transfer()": reference/transfer.md
  - "Examples":
      - "Audio streams":
          - "Record audio": examples/record-audio.md
          - "Stream audio": examples/stream-audio.md
      - "Call control":
          - "Answer call": examples/answer-call.md
          - "Transfer call": examples/transfer-call.md
  - "Support": support.md
